# Generated by Django 5.1.4 on 2024-12-28 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('contrats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat à Durée Indéterminée'), ('CDD', 'Contrat à Durée Déterminée'), ('STAGE', 'Stage'), ('AUTRE', 'Autre')], max_length=6)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('periode_essai_debut', models.DateField(blank=True, null=True)),
                ('periode_essai_fin', models.DateField(blank=True, null=True)),
                ('alerte_renouvellement_envoyee', models.BooleanField(default=False)),
                ('archive', models.BooleanField(default=False)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='app.personnel')),
            ],
        ),
        migrations.DeleteModel(
            name='Offre_emploi',
        ),
        migrations.DeleteModel(
            name='Recrutements',
        ),
    ]
