# Generated by Django 5.1.4 on 2024-12-28 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.IntegerField()),
                ('Position', models.CharField(max_length=40)),
                ('skills', models.CharField(max_length=254)),
                ('training', models.CharField(max_length=254)),
                ('hireDate', models.DateField()),
                ('Adresse', models.CharField(max_length=254)),
                ('jours_restants', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('IdService', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nameservice', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('evaluation_type', models.CharField(choices=[('Annual', 'Annual'), ('Semi-Annual', 'Semi-Annual')], default='Annual', max_length=20)),
                ('criteria', models.JSONField(default=dict)),
                ('performance_rating', models.IntegerField()),
                ('skills_developed', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('Annuel', 'Congé Annuel'), ('Maladie', 'Congé Maladie'), ('Maternité', 'Congé Maternité'), ('Paternité', 'Congé Paternité'), ('Sans Solde', 'Congé Sans Solde'), ('Autre', 'Autre')], max_length=20)),
                ('date_debut', models.DateField(verbose_name='Date de Début')),
                ('date_fin', models.DateField(verbose_name='Date de Fin')),
                ('jours_utilises', models.IntegerField(verbose_name='Jours Utilisés')),
                ('jours_restants', models.IntegerField(verbose_name='Jours Restants')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='app.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='IdService',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service'),
        ),
    ]
