# Generated by Django 5.1.4 on 2025-01-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_personnel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender'),
        ),
    ]
