# Generated by Django 5.1.4 on 2025-01-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_personnel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='date_naissance',
            field=models.DateField(default='1999-10-4'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Gender'),
        ),
    ]
