# Generated by Django 5.1.4 on 2025-01-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_personnel_date_naissance_alter_personnel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='date_naissance',
            field=models.DateField(),
        ),
    ]
