# Generated by Django 5.1.4 on 2025-01-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_personnel_date_naissance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conge',
            name='jours_restants',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='jours_restants',
        ),
        migrations.AddField(
            model_name='personnel',
            name='jours_annuels',
            field=models.IntegerField(default=30, verbose_name='Jours de Congé Annuel'),
        ),
        migrations.AlterField(
            model_name='conge',
            name='jours_utilises',
            field=models.IntegerField(editable=False, verbose_name='Jours Utilisés'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender'),
        ),
    ]
