# Generated by Django 5.1.4 on 2025-01-19 01:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_personnel_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='Phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits long and start with 05, 06, or 07.', regex='^(05|06|07)\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='date_naissance',
            field=models.DateField(default=datetime.date(1999, 1, 1)),
        ),
    ]
