# Generated by Django 5.1.4 on 2024-12-28 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_absence', models.DateField()),
                ('is_absent', models.BooleanField(default=True)),
                ('id_employe', models.ManyToManyField(to='app.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id_salaire', models.AutoField(primary_key=True, serialize=False)),
                ('date_paie', models.DateField()),
                ('montant', models.FloatField(default=0)),
                ('salaire_base', models.IntegerField(default=30000)),
                ('salaire_jour', models.IntegerField(default=2000)),
                ('absences', models.IntegerField(default=0)),
                ('massrouf_fois', models.IntegerField(default=0)),
                ('massrouf_annuel', models.IntegerField(default=0)),
                ('massrouf_mensuel', models.IntegerField(default=0)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personnel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('id_employe', 'date_paie'), name='unique_salaire_per_employee_per_month')],
            },
        ),
    ]
