# Generated by Django 5.1.4 on 2025-01-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaire',
            name='prime_festive',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salaire',
            name='prime_performance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='salaire',
            name='prime_total',
            field=models.FloatField(default=0),
        ),
    ]
