# Generated by Django 5.1.4 on 2025-01-14 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_personnel_date_naissance'),
        ('salaire', '0002_salaire_prime_festive_salaire_prime_performance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('date_absence', 'id_employe')},
        ),
        migrations.RemoveField(
            model_name='presence',
            name='id_employe',
        ),
        migrations.AddField(
            model_name='presence',
            name='id_employe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.personnel'),
        ),
    ]
