# Generated by Django 5.1.4 on 2025-01-14 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_personnel_date_naissance'),
        ('salaire', '0003_alter_presence_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='id_employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personnel'),
        ),
    ]
