# Generated by Django 5.1.4 on 2025-01-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0005_alter_presence_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massrouf',
            name='annee',
            field=models.IntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='massrouf',
            name='massrouf_fois',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='massrouf',
            name='montant',
            field=models.FloatField(default=0),
        ),
    ]
