# Generated by Django 5.1.4 on 2025-01-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salaire', '0006_alter_massrouf_annee_alter_massrouf_massrouf_fois_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massrouf',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
