# Generated by Django 5.1.4 on 2025-01-18 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoris', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite_section',
            name='section_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_sections', to='favoris.section'),
        ),
        migrations.AlterField(
            model_name='favorite_section',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
