# Generated by Django 5.1.4 on 2025-01-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoris', '0002_alter_favorite_section_section_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
