# Generated by Django 5.1.4 on 2024-12-28 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre_emploi',
            fields=[
                ('id_offre', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('statut', models.CharField(max_length=50)),
                ('date_publication', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recrutements',
            fields=[
                ('id_poste', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('titre', models.CharField(max_length=50)),
                ('exigences', models.CharField(max_length=200)),
                ('statut', models.CharField(max_length=50)),
                ('date_publication', models.DateField()),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.service')),
            ],
        ),
    ]
