# Generated by Django 5.1.4 on 2024-12-31 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recrutements',
            new_name='Recrutement',
        ),
    ]
