# Generated by Django 5.1.4 on 2025-01-03 17:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0004_offre_emploi_lieu_offre_emploi_type_contrat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id_candidature', models.AutoField(primary_key=True, serialize=False)),
                ('nom_candidat', models.CharField(max_length=100, verbose_name='Candidate Name')),
                ('email_candidat', models.EmailField(max_length=254, verbose_name='Candidate Email')),
                ('cv', models.FileField(upload_to='candidatures/cv/', verbose_name='Resume')),
                ('lettre_motivation', models.TextField(blank=True, null=True, verbose_name='Cover Letter')),
                ('date_candidature', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Application Date')),
                ('statut_candidature', models.CharField(choices=[('En attente', 'Pending'), ('Accepté', 'Accepted'), ('Rejeté', 'Rejected')], default='En attente', max_length=20, verbose_name='Application Status')),
                ('id_offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='recrutement.offre_emploi')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_candidature'],
            },
        ),
    ]
