# Generated by Django 5.1.4 on 2025-01-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0005_candidature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidature',
            name='statut_candidature',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Accepté', 'Accepté'), ('Rejeté', 'Rejeté')], default='En attente', max_length=20, verbose_name='Application Status'),
        ),
    ]
