# Generated by Django 5.1.4 on 2025-01-03 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0007_candidature_telephone_candidat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id_entretien', models.AutoField(primary_key=True, serialize=False)),
                ('date_entretien', models.DateTimeField(verbose_name='Interview Date')),
                ('lieu_entretien', models.CharField(max_length=255, verbose_name='Interview Location')),
                ('statut_entretien', models.CharField(default='Scheduled', max_length=50, verbose_name='Interview Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Interview Notes')),
                ('id_candidature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='recrutement.candidature')),
            ],
            options={
                'verbose_name': 'Entretien',
                'verbose_name_plural': 'Entretiens',
            },
        ),
    ]
